Katie enhancement hover
SilveradoPolicy/silverado pull request #135
Opened 2021-03-01 14:47 UTC by kcbreuil

@asasmith first pass at this. obviously need to tweak styling, etc but let me know what you think. I really think an on hover makes more sense then on click. Not sure a user would actually click a name, unless it had some sort of CTA.

2021-03-01 21:50 UTC, asasmith requested changes

2021-03-01 21:50 UTC, asasmith commented on src/components/strategicAdvisor.js
>          <div>
Let's make the entire div "clickable". If you be able to use the `role` attribute to fix the eslint error (`role="button"`).

2021-03-01 21:50 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                        x
Let's use `react-icons` here. I'd use `MdClose` from `Material Design icons`. Should look like this:
```
import { MdClose } from "react-icons/md";

<MdClose onClick={} />    
```

2021-03-01 21:50 UTC, asasmith commented on src/components/strategicAdvisor.js
> +        top: '60%',
Change this to `50%`

2021-03-01 21:50 UTC, asasmith commented on src/components/strategicAdvisor.js
> +    }
Is this necessary? It might be, but if it's not let's remove it.

2021-03-01 21:50 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                        x
Actually, keep this wrapped in a button element with `role=button`. Then absolute position the button using `absolute top-0 right-0` (I think those are the right classes).

2021-03-01 22:43 UTC, asasmith commented on src/components/strategicAdvisor.js
>          <div>
Should also add the tw class `cursor-pointer` to the div so there's a visual clue something happens there.

2021-03-01 22:43 UTC, kcbreuil commented on src/components/strategicAdvisor.js
>          <div>
@asasmith I tried this earlier and it did not work (as in i kept getting lint error after lint error)

2021-03-01 22:50 UTC, asasmith commented on src/components/strategicCouncil.js
> +                'Senior Fellow, Freeman Spogli Institute for International Studies at Stanford University; Davies Family Senior Fellow at the Hoover Institution',
Let's move this to a separate pr

2021-03-01 22:54 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                    <label>{advisorFullName}</label>
I don't think this needs to be wrapped in a `<label>` element

2021-03-01 23:00 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                    <br />
remove `<br>`

2021-03-01 23:01 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                    >
Can we do this with styled components and tailwind?

Also, I think it should be `role=button` not `type=button` but double check what the semantic difference is.

2021-03-02 01:21 UTC, asasmith requested changes

2021-03-02 01:45 UTC, kcbreuil commented on src/components/strategicAdvisor.js
> +            <ButtonDiv
@asasmith no because it breaks the modals logic. I tried that

2021-03-02 18:59 UTC, asasmith requested changes

2021-03-02 18:59 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                role="button"
I don't think you can use `type` on an element that isn't `button`. `role` should be sufficient here.

2021-03-02 18:59 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                            }}
Use style components for any elements we're styling. Remove `<br>` and use margin to adjust spacing.

2021-03-02 18:59 UTC, asasmith commented on src/components/strategicAdvisor.js
> +    // }
Remove comments.

2021-03-02 18:59 UTC, asasmith commented on src/components/strategicAdvisor.js
> +
Add `Modal.setAppElement('#___gatsby');` before `setIsOpen`

2021-03-02 18:59 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                onKeyDown={toggleModal}
Create a separate handler for `keydown` that calls `toggleModal` if the enter key is pressed.

2021-03-02 20:28 UTC, asasmith requested changes

2021-03-02 20:28 UTC, asasmith commented on src/components/imageWithName.js
> +                        }}
Remove style prop

2021-03-02 20:28 UTC, asasmith commented on src/components/imageWithName.js
> +                    </h1>
can this be a styled component too?

2021-03-02 20:28 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                        >
Change to a styled component with tailwind classes

2021-03-02 20:28 UTC, asasmith commented on src/components/strategicAdvisor.js
> +                                right: '10px',
Remove style prop

2021-03-05 00:08 UTC, asasmith approved these changes

2021-03-05 00:08 UTC, merged