Katie news page
SilveradoPolicy/silverado pull request #141
Opened 2021-04-02 19:56 UTC by kcbreuil

2021-04-03 13:54 UTC, asasmith requested changes

2021-04-03 13:54 UTC, asasmith commented on src/pages/news.js
> +            </Section>
Can you move this to it's own component?

2021-04-03 13:54 UTC, asasmith commented on src/pages/news.js
> +`;
The items in this wrapper should stack on small screens.

2021-04-03 13:54 UTC, asasmith commented on src/components/newsEventList.js
> +import SingleEvent from './singleEvent';
It's maybe a little nitpicky, but I'm concerned about this naming convetion. I think `EventPreview` would be better but am open to having a discussion about it.

2021-04-03 13:54 UTC, asasmith commented on src/components/singleEvent.js
> +    ${tw``}
If you're not using the `tw` macro for anything I think it's fine to omit it.

2021-04-03 13:54 UTC, asasmith commented on src/components/singleEvent.js
> +            <Heading className="font-wt-bold">{heading}</Heading>
Can this class be added to the styled-component?

2021-04-03 13:54 UTC, asasmith commented on src/components/newsFeatureComponent.js
> +            <Heading className="font-wt-bold">{heading}</Heading>
Can this classname be added to the styled component?

2021-04-03 13:54 UTC, asasmith commented on src/components/singleEvent.js
> +        width: 45%;
What is the width declaration for?

2021-04-04 01:28 UTC, kcbreuil commented on src/components/singleEvent.js
> +            <Heading className="font-wt-bold">{heading}</Heading>
@asasmith no remember we have to do this for this project.

2021-04-05 16:42 UTC, asasmith commented on src/components/singleEvent.js
> +            <Heading className="font-wt-bold">{heading}</Heading>
ah, right. I have a fix for that now. Let's make a note to update this at some point.

2021-04-05 16:57 UTC, kcbreuil commented on src/pages/news.js
> +            </Section>
@asasmith I had tried to do that and was having issues with the prop drilling portion of it. I can try again but wasnt sure how much time we wanted to spend on it just to move the component one layer down.

2021-04-05 17:02 UTC, kcbreuil commented on src/components/singleEvent.js
> +        width: 45%;
So it takes up the percentage of the screen. Previously you had given it a set width, but i want it to take up 45% of the screen (half the page)

2021-04-05 17:19 UTC, kcbreuil commented on src/components/newsEventList.js
> +import SingleEvent from './singleEvent';
@asasmith I changed it but I also think youre thinking of the component on the left side of the page, where we preview a single event?

2021-04-05 17:20 UTC, kcbreuil commented on src/components/newsFeatureComponent.js
> +            <Heading className="font-wt-bold">{heading}</Heading>
@asasmith Same thing, we have been using this convention for this project to add weights to text

2021-04-05 17:24 UTC, kcbreuil commented on src/components/newsEventList.js
> +import SingleEvent from './singleEvent';
<img width="305" alt="Screen Shot 2021-04-05 at 1 23 48 PM" src="https://user-images.githubusercontent.com/61708936/113603679-38b69680-9612-11eb-9686-a0b9fd0e8ab0.png">
this is considered a single event ^^, we map through all the events in the list

2021-04-05 17:28 UTC, asasmith commented on src/pages/news.js
> +            </Section>
Yeah I think it should be its own component. Looking at the code I think you should be passing an array of objects (eventsInfo). Let me know if you have any questions.

2021-04-05 17:31 UTC, asasmith commented on src/components/newsEventList.js
> +import SingleEvent from './singleEvent';
The item on the left is a blog post, right?

2021-04-05 17:34 UTC, kcbreuil commented on src/components/singleEvent.js
> +        width: 45%;
@asasmith Added a media query for this so it will change to 95% of the screen on small screens as well so now its responsive

2021-04-05 17:34 UTC, kcbreuil commented on src/pages/news.js
> +            </Section>
@asasmith let me know how you'd like to proceed

2021-04-05 17:35 UTC, asasmith commented on src/pages/news.js
> +            </Section>
I'm not sure what the issue was so that's a difficult question for me to answer. This should be extracted to it's own component.

2021-04-05 17:56 UTC, asasmith commented on src/components/singleEvent.js
> +        width: 45%;
Absolutely positioned items rely on an ancestor having `position: relative`. I think you're accidentally avoiding this bu not declaring a `top` or `bottom` position. I don't think we should be relying on the width of the page to set the width of this item (ie, it should always be 100% of it's parent element).

I had `position: relative` on the parent (tw class `relative`) and set the width to be `100%` of that parent element. 

I think it's best to add `position: relative` to the parent element and make this `width: 100%`.

2021-04-05 23:53 UTC, kcbreuil commented on src/components/singleEvent.js
> +        width: 45%;
@asasmith i had tried that originally and it did not position correctly, hence utilizing different properties

2021-04-06 00:09 UTC, kcbreuil commented on src/components/newsEventList.js
> +import SingleEvent from './singleEvent';
@asasmith yes, but I think we squared this away I renamed everything to eventPreview

2021-04-06 00:10 UTC, kcbreuil commented on src/pages/news.js
> +            </Section>
Extracted and ready for review

2021-04-06 14:21 UTC, asasmith requested changes

2021-04-06 14:21 UTC, asasmith commented on src/components/eventPreview.js
> +`;
I should've been more clear when we were discussing this.

The first parent element of the `before` element is `<StyledEventPreview>`

I think right now you've added `relative` to `<StyledEventsList>`

This is still working because you haven't declared a position `top/right/bottom/left` on the `before` element. Once you add one of those values they're not positioned like you would expect (and I think we should always add those values to positioned elements to clearly communicate how/where they're positioned).

So you'll want to add `relative` to `<StyledEventPreview>` and `top-0 left-0` to the `:before` pseudo element. You should be able to remove it from the `<StyledEventsList>` component. 

Let me know if you have any questions.

2021-04-07 15:02 UTC, asasmith approved these changes

2021-04-07 15:06 UTC, asasmith approved these changes

2021-04-07 15:06 UTC, merged