pillar description component
SilveradoPolicy/silverado pull request #143
Opened 2021-04-04 01:22 UTC by kcbreuil

2021-04-07 15:04 UTC, asasmith requested changes

2021-04-07 15:04 UTC, asasmith commented on src/components/pillarDescription.js
> +// import PropTypes from 'prop-types';
If we're not using this now let's omit it

2021-04-07 15:15 UTC, kcbreuil commented on src/components/pillarDescription.js
> +// import PropTypes from 'prop-types';
@asasmith We will need it once we refactor to export the data object

2021-04-07 15:17 UTC, kcbreuil commented on src/components/pillarDescription.js
> +// import PropTypes from 'prop-types';
@asasmith I can update now if you'd like?

2021-04-08 16:14 UTC, asasmith commented on src/components/pillarDescription.js
> +// import PropTypes from 'prop-types';
please. Let's avoid this pattern as much as possible.

2021-04-08 23:58 UTC, asasmith approved these changes

2021-04-08 23:58 UTC, merged