test edit
SilveradoPolicy/silverado pull request #170
Opened 2021-04-21 18:43 UTC by kcbreuil

2021-04-21 18:46 UTC, asasmith requested changes

2021-04-21 18:46 UTC, asasmith commented on web/src/components/pillarComponent.js
> +    ${tw`bg-white transform -translate-y-20 md:-translate-y-1/2 flex flex-col justify-center mx-10`}
I know this is just to demo the difference in the Y translate but I would add the `container` class either way

2021-04-21 19:06 UTC, kcbreuil commented on web/src/components/pillarComponent.js
> +    ${tw`bg-white transform -translate-y-20 md:-translate-y-1/2 flex flex-col justify-center mx-10`}
@asasmith updated!

2021-04-22 20:08 UTC, asasmith approved these changes

2021-04-22 20:09 UTC, merged