Katie build out studio
SilveradoPolicy/silverado pull request #172
Opened 2021-04-22 19:06 UTC by kcbreuil

2021-04-23 17:28 UTC, asasmith requested changes

2021-04-23 17:28 UTC, asasmith commented on studio/schemas/documents/event.js
> +        },
Move this object to the beginning of the `fields` array so that this field is first in the sanity ui

2021-04-23 17:28 UTC, asasmith commented on studio/schemas/documents/event.js
> +            name: 'DateAndTime',
Switch the `name` and `title` lines so that `name` appears first. Lower case `d` in `DateAndTime`

2021-04-23 17:28 UTC, asasmith commented on studio/schemas/documents/event.js
> +};
Add an `orderings` array and a `preview` object as seen [here](https://github.com/bckrm/gianna-biscontini/blob/main/studio/schemas/documents/post.js#L46-L83). This will makes sure that the list of events is can be viewed in asc/desc order in sanity. The `preview` object tells sanity what fields to use for the preview display.

2021-04-23 17:28 UTC, asasmith commented on studio/schemas/documents/event.js
> +    title: 'Event',
Pluralize `Event`

2021-04-23 17:28 UTC, asasmith commented on studio/schemas/documents/newsIndexPage.js
> +    __experimental_actions: ['create', 'update', 'delete', 'publish'],
`delete` should not be present here. Try removing it from the array (for some reason I think this will break stuff). If removing it from the array breaks something just comment it out like [this](https://github.com/bckrm/gianna-biscontini/blob/main/studio/schemas/documents/aboutPage.js#L5-L10).

2021-04-23 17:28 UTC, asasmith commented on studio/schemas/documents/post.js
> +        },
Move this object to the first item in the `fields` array.

2021-04-23 17:28 UTC, asasmith commented on studio/schemas/documents/post.js
> +        },
Create an `author` or `teamMember` document and use a reference field to associate a single author with a post. We'll be able to use that new `author/teamMember` document for the team bio section.

2021-04-23 17:28 UTC, asasmith commented on studio/schemas/schema.js
> +        bodyPortableText,
Alphabetical order please :)

2021-04-23 17:28 UTC, asasmith commented on studio/static/structure/deskStructure.js
> +                    !['indexPage', 'newsIndexPage', 'eventIndexPage'].includes(
Alphabetical order please :)

2021-04-23 17:28 UTC, asasmith commented on studio/static/structure/deskStructure.js
> +                .title('News')
Change this title to `News Page` to clearly communicate what it is in the sanity ui.

2021-04-23 17:28 UTC, asasmith commented on studio/static/structure/deskStructure.js
> +                .title('Events')
Change this title to `Events Page` to clearly communicate what it is in the sanity ui.

2021-04-26 12:57 UTC, asasmith requested changes

2021-04-26 12:57 UTC, asasmith commented on studio/schemas/documents/post.js
> +        },
This one was missed. To be clear, I think it's best that the `title` object is the first item in the `fields` array.

2021-04-26 12:57 UTC, asasmith commented on studio/schemas/documents/eventIndexPage.js
> +        },
Will we need a field for the hero image?

2021-04-26 12:57 UTC, asasmith commented on studio/schemas/documents/post.js
> +    ],
Sorry that I missed this one. This document will need an `orderings` and `preview` as well. (same as the event document)

2021-04-26 17:05 UTC, kcbreuil commented on studio/schemas/documents/eventIndexPage.js
> +        },
@asasmith I thought we would query the event card which has the hero image. What do you think?

2021-04-26 17:31 UTC, asasmith commented on studio/schemas/documents/eventIndexPage.js
> +        },
Not sure I'm following. In the sanity ui the fields will be listed in the order that they're in the `fields` array. I think visually it makes more sense for the title/name to be the first field presented to the user.

2021-04-26 17:36 UTC, asasmith commented on studio/schemas/documents/eventIndexPage.js
> +        },
Please confirm that is how this is supposed to work. It might be. I assumed that the hero image was unique to the page, not pulling from the featured event

2021-04-26 17:37 UTC, asasmith commented on studio/schemas/documents/eventIndexPage.js
> +        },
Actually, if images aren't required this won't work and we would need an image set at the page level. Please confirm if images are required for events.

2021-04-26 19:21 UTC, kcbreuil commented on studio/schemas/documents/eventIndexPage.js
> +        },
@asasmith to be honest, I imagined that the image would come from the 'featuredEvent' which is an event but again, I could be wrong, but that makes the most sense to me.

2021-04-26 19:44 UTC, asasmith commented on studio/schemas/documents/eventIndexPage.js
> +        },
It'll be the featured event reference, for now :)

2021-04-26 19:44 UTC, asasmith approved these changes

2021-04-26 19:49 UTC, merged