'image and merge'
SilveradoPolicy/silverado pull request #173
Opened 2021-04-26 20:44 UTC by kcbreuil

2021-04-26 22:13 UTC, asasmith requested changes

2021-04-26 22:13 UTC, asasmith commented on studio/schemas/documents/eventIndexPage.js
> +            type: 'image',
I think there's an image object created that has alt text fields. Can we use that instead?

2021-04-26 23:02 UTC, kcbreuil commented on studio/schemas/documents/eventIndexPage.js
> +            type: 'image',
@asasmith  done, I kept the name and title Hero Image, let me know if you think it should be mainImage

2021-04-27 12:52 UTC, asasmith approved these changes

2021-04-27 12:53 UTC, merged