single event page WIP
SilveradoPolicy/silverado pull request #181
Opened 2021-04-29 03:24 UTC by kcbreuil

2021-04-30 13:21 UTC, asasmith requested changes
I think we need a little more bottom padding (underneath the person's title).

![Screen Shot 2021-04-30 at 9 20 51 AM](https://user-images.githubusercontent.com/11489171/116700970-5d91f580-a995-11eb-8cc9-54360630bc7e.png)

2021-04-30 13:27 UTC, asasmith commented on web/src/components/speakerCard.js
> +        ${tw``}
Also, these should not be `<h1>`'s.

2021-04-30 15:29 UTC, kcbreuil commented on web/src/components/registration.js
> +            <StyledButton className="font-wt-thin">Register</StyledButton>
@asasmith ah okay, cool, thank you

2021-04-30 15:35 UTC, asasmith commented on web/src/components/imageNoName.js
> +    ${tw`mb-4 mx-auto h-28 w-28 overflow-hidden rounded-full`}
It might not be. I thought it was used for images on the `About` page. If that's not the case disregard

2021-04-30 21:08 UTC, kcbreuil commented
> I think we need a little more bottom padding (underneath the person's title).
> 
> ![Screen Shot 2021-04-30 at 9 20 51 AM](https://user-images.githubusercontent.com/11489171/116700970-5d91f580-a995-11eb-8cc9-54360630bc7e.png)

I could not get this to respond to any margin or padding beneath the name. Do you have any suggestions?

2021-04-30 21:23 UTC, kcbreuil commented
> > I think we need a little more bottom padding (underneath the person's title).
> > ![Screen Shot 2021-04-30 at 9 20 51 AM](https://user-images.githubusercontent.com/11489171/116700970-5d91f580-a995-11eb-8cc9-54360630bc7e.png)
> 
> I could not get this to respond to any margin or padding beneath the name. Do you have any suggestions?

@asasmith also does it only look like that with dev tools open?

![Uploading Screen Shot 2021-04-30 at 5.21.16 PM.png…]()

2021-04-30 21:24 UTC, kcbreuil commented on web/src/components/eventInfoHero.js
> +`;
@asasmith I dont think so, it will shrink the image and thats not the look we are going for here? 

<img width="1280" alt="Screen Shot 2021-04-30 at 5 24 22 PM" src="https://user-images.githubusercontent.com/61708936/116755771-ec743180-a9d8-11eb-9681-27d3239ae879.png">

2021-04-30 21:43 UTC, asasmith commented
Couple of small issues on mobile

<img width="352" alt="Screen Shot 2021-04-30 at 5 42 47 PM" src="https://user-images.githubusercontent.com/11489171/116757163-8ccb5580-a9db-11eb-93f2-ba248fbee387.png">

2021-04-30 21:57 UTC, asasmith commented on web/src/components/eventInfoHero.js
> +`;
yeah, this doesn't look right either.

2021-05-03 13:23 UTC, asasmith requested changes

2021-05-03 13:23 UTC, asasmith commented on web/src/components/eventInfoCard.js
> +    ${tw`flex justify-center flex-col md:flex-row bg-white mx-4 px-4 md:mx-10 transform -translate-y-28 md:-translate-y-1/4 lg:-translate-y-2/4`}
I do think we need to add `container` here. 

Without the `container` class this div get's too big on large screens. You'll also need to remove any margin classes you've added.

<img width="1679" alt="Screen Shot 2021-05-03 at 9 17 03 AM" src="https://user-images.githubusercontent.com/11489171/116881030-c2955780-abf0-11eb-82c0-3c8e5913dc8f.png">

With `container`
<img width="1678" alt="Screen Shot 2021-05-03 at 9 16 48 AM" src="https://user-images.githubusercontent.com/11489171/116881063-cb862900-abf0-11eb-832a-54c78aa45bae.png">

2021-05-03 13:23 UTC, asasmith commented on .gitignore
> +.env
I think you need to pull down the most recent changes in `bckrm-staging`. This should already be there.

2021-05-04 18:44 UTC, asasmith approved these changes

2021-05-04 18:44 UTC, merged